### ISSUE TITLE
Thermal scattering data

### ISSUE THREAD

**Issue by AI-Pranto** [openmc-data-storage/openmc_data_downloader#14]
@Shimwell It's really amazing I :heart: this.  

One question, How to install thermal scattering data?

**Comment by Shimwell** [comment]
Yes good question, currently it can't perform that download.

If I can map each s(a,b) thermal cross section to a particular element or elements then I can add a flag to include them or not.

Currently these are processed but not included in the database of available cross sections.

I shall look into it.

**Comment by Shimwell** [comment]
Ok i think I have a method for the command line tool

I can add a flag for -sab and accept a list of stings. Each entry must be in this list of acceptable names.

The input strings can be checked against acceptable names define here https://github.com/openmc-dev/openmc/blob/efcc0c158edcc3e389eb20a5c5ffc4e0a65ef554/openmc/data/thermal.py#L30-L77

Then the unique sab names can be match to the urls in the endf list of h5 files containing thermal cross sections (botton of [this](https://github.com/openmc-data-storage/ENDF-B-VII.1-NNDC/tree/main/h5_files/neutron) page

For the api usage I notice the ```openmc.material.add_s_alpha_beta``` sets a ```._sab``` attribute so that can be used to check if there are sab requirments in the material object

https://github.com/openmc-dev/openmc/blob/efcc0c158edcc3e389eb20a5c5ffc4e0a65ef554/openmc/material.py#L697

Sorry this is taking me a little while as I have a few projects to close out at the moment

**Comment by Shimwell** [comment]
@AI-Pranto I have had a go at adding this feature in the latest PR merge https://github.com/openmc-data-storage/openmc_data_downloader/pull/16 there are a few examples on the readme.

I am keen to improve it if you have any suggestions

**Comment by AI-Pranto** [comment]
Sorry for the late response here.

LGTM, Thanks @shimwell! 

Just one last request here, Currently we have neutrons and Tsl data only at a single temperature `294`. Can we include neutrons data at `250 K`, `293.6 K`, `600 K`, `900 K`, `1200 K`, and `2500 K`? We can update our current [ENDF-B-VII.1-NNDC data storage](https://github.com/openmc-data-storage/ENDF-B-VII.1-NNDC) by downloading pre-processed data from [openmc-data](https://openmc.org/official-data-libraries/) Is it ok with you?
@Shimwell Did you face data storage limit in github?

**Comment by Shimwell** [comment]
Yep there is a storage limit per repo so I guess that each temperature could be a separate repo to avoid that.

The repos on this organisation currently make use of[ these scripts](https://github.com/openmc-dev/data/) to download data and process it into h5 data.

They are all templates a single repository with library specific modifications

So I would need another base repository to template that would take a different approach

The new template would download from https://openmc.org/official-data-libraries/ extract and self commit to the repo using a GitHub action

This might take a little while to sort out and then extend to do different temperatures but it is certainly now on the todo list, thanks for the suggestion

**Comment by AI-Pranto** [comment]
Thanks, @Shimwell :)

**Comment by AI-Pranto** [comment]
Fix by #16
